package com.shoppingcart.apps.controller;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.shoppingcart.apps.entity.Account;
import com.shoppingcart.apps.model.User;
import com.shoppingcart.apps.repository.UserRepository;

@Controller
public class AuthenticationController {

   // private static final String template = "Hello, %s!";
   // private final AtomicLong counter = new AtomicLong();
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	 @RequestMapping(value = { "/api/validateUser" })
	    public @ResponseBody User validateUser(HttpServletRequest request,Model model, @RequestParam("userName") String userName,@RequestParam("password") String password) {
	    	Account account = userRepository.validateUser(userName,password);
	    	User user=null;
	        System.out.println("Account= " + account);
	        if(account!=null){	 
	        	user=new User(account.getUserName(),account.getUserRole(),account.isActive(),account.getPassword());	        	
	        }
	        
	        return user;	 
	        
	    }
   

}
